name: Optimize

on:
  workflow_dispatch: {}
  schedule:
    - cron: '30 1 * * *'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - uses: actions/checkout@v4
      - name: Start Trino
        run: ./bin/run-trino.sh
      - name: Optimize tables
        run: |
          docker exec \
            trino \
            trino --catalog trinocicd --schema v2 \
            -f /sql/optimize.sql
      - name: Dump Trino logs
        if: always()
        run: |
          docker logs trino
