name: Incremental data sync

on:
  workflow_dispatch: {}
  schedule:
    - cron: '30 */2 * * *'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TRINO_REST_VERSION: "0.144"
      GITHUB_OWNER: trinodb
      GITHUB_REPO: trino
      TRINO_DEST_SCHEMA: trinocicd.v2
      TRINO_SRC_SCHEMA: github.default
      EMPTY_INSERT_LIMIT: 5
      # TODO temporarily removed artifacts since they're causing OOMs, figure out a different way to fetch them
      SYNC_TABLES: runs,jobs,steps,check_suites,check_runs,check_run_annotations,pulls,pull_commits,pull_stats,review_comments,reviews,issues,issue_comments,commits,teams,members
    steps:
      - uses: actions/checkout@v4
      - name: Start Trino
        run: |
          ./bin/run-trino.sh
          SERVER_IP=$(docker inspect --format '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' "$CONTAINER_ID")
          echo "SERVER_IP=$SERVER_IP" >> $GITHUB_ENV
      - name: Run Sync
        run: |
          docker run \
            -e GITHUB_OWNER \
            -e GITHUB_REPO \
            -e TRINO_DEST_SCHEMA \
            -e TRINO_SRC_SCHEMA \
            -e EMPTY_INSERT_LIMIT \
            -e SYNC_TABLES \
            -e TRINO_URL=jdbc:trino://$SERVER_IP:8080/github/default \
            --rm \
            nineinchnick/trino-rest:$TRINO_REST_VERSION \
            java -cp "/usr/lib/trino/plugin/github/*" pl.net.was.rest.github.Sync
      - name: Run Sync for Starburst Teams
        run: |
          docker run \
            -e GITHUB_OWNER=starburstdata \
            -e GITHUB_REPO \
            -e TRINO_DEST_SCHEMA \
            -e TRINO_SRC_SCHEMA \
            -e EMPTY_INSERT_LIMIT \
            -e SYNC_TABLES=teams,members \
            -e TRINO_URL=jdbc:trino://$SERVER_IP:8080/github/default \
            --rm \
            nineinchnick/trino-rest:$TRINO_REST_VERSION \
            java -cp "/usr/lib/trino/plugin/github/*" pl.net.was.rest.github.Sync
      - name: Dump Trino logs
        if: always()
        run: |
          docker logs trino
