name: Incremental data sync

on:
  workflow_dispatch: {}
  schedule:
    - cron: '30 */2 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TRINO_VERSION: 375
      TRINO_REST_VERSION: "0.58"
      GITHUB_OWNER: trinodb
      GITHUB_REPO: trino
      TRINO_DEST_SCHEMA: hive.v2
      TRINO_SRC_SCHEMA: github.default
      EMPTY_INSERT_LIMIT: 5
      # sync for reviews takes too long, sync for review_comments is broken because Github return a Server Error
      SYNC_TABLES: runs,jobs,steps,check_suites,check_runs,check_run_annotations,pulls,issues,issue_comments,commits,artifacts
    steps:
      - uses: actions/checkout@v2
      - name: Download trino-rest
        run: |
          curl -fLOsS https://github.com/nineinchnick/trino-rest/releases/download/v$TRINO_REST_VERSION/trino-rest-github-$TRINO_REST_VERSION.zip
          unzip trino-rest-github-$TRINO_REST_VERSION.zip
      - name: Start Trino
        run: |
          CONTAINER_ID=$(docker run \
            -v $(pwd)/trino-rest-github-$TRINO_REST_VERSION:/usr/lib/trino/plugin/github \
            -v $(pwd)/catalog/github.properties:/etc/trino/catalog/github.properties \
            -v $(pwd)/catalog/hive.properties:/etc/trino/catalog/hive.properties \
            -v $(pwd)/hive-cache:/opt/hive-cache \
            -v $(pwd)/sql:/sql \
            -e AWS_ACCESS_KEY_ID \
            -e AWS_SECRET_ACCESS_KEY \
            -e AWS_REGION \
            -e GITHUB_TOKEN \
            -p 8080:8080 \
            --name trino \
            -d \
            trinodb/trino:$TRINO_VERSION)
          SERVER_IP=$(docker inspect --format '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' "$CONTAINER_ID")
          echo "CONTAINER_ID=$CONTAINER_ID" >> $GITHUB_ENV
          echo "SERVER_IP=$SERVER_IP" >> $GITHUB_ENV
          i=0
          until docker inspect "${CONTAINER_ID}" --format "{{json .State.Health.Status }}" | grep -q '"healthy"'; do
              if [[ $((i++)) -ge 10 ]]; then
                  echo "🚨 Too many retries waiting for Trino to start"
                  docker logs "${CONTAINER_ID}"
                  exit 1
              fi
              sleep 10
          done
          docker logs "${CONTAINER_ID}"
      - name: Run Sync
        run: |
          docker run \
            -e GITHUB_OWNER \
            -e GITHUB_REPO \
            -e TRINO_DEST_SCHEMA \
            -e TRINO_SRC_SCHEMA \
            -e EMPTY_INSERT_LIMIT \
            -e SYNC_TABLES \
            -e TRINO_URL=jdbc:trino://$SERVER_IP:8080/github/default \
            --rm \
            nineinchnick/trino-rest:$TRINO_REST_VERSION \
            java -cp "/usr/lib/trino/plugin/github/*" pl.net.was.rest.github.Sync
      - name: Optimize tables
        run: |
          docker exec \
            trino \
            trino --catalog hive --schema v2 \
            -f /sql/optimize.sql
